name: release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-release:
    strategy:
      matrix:
        os: ['windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Nuget Packages
      run: nuget restore .\packages.config -PackagesDirectory .\packages\
    - name: Build Init
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_init.cmd
    - name: Build Solution
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_release.cmd
    
    # Add this step to upload x64 artifacts
    - name: Upload x64 Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: systeminformer-x64
        path: |
          bin\Release64\**
